### ISSUE TITLE
Editor functionality lost when using FileSaver.js

### ISSUE THREAD

**Issue by kardazs** [yabwe/medium-editor#667] opened 2015-06-03 22:43 UTC
Hi,

I have a weird issue maybe more browser related than script.

I am using the ME in a page to edit a few table cell (TD) content which is wrapped inside a DIV. Works everything fine.

Then I have a button which triggering the FileSaver.JS SaveAs() function. With JQuery I reading the DIV content and saving it.

Now when the Open or Save dialog pops up (the generic popup) I can save the file and after if I try to edit the text:
- the toolbar appears 
- it is detecting that the selected text already has formating (eg. bold or italic)
- the anchor popup appears if I clicking on the toolbar

But no format applied on the text.

Even if I destroy and setup the ME or just reinit it againg no change. The script working, the element is still editable because I can type text in but I can't format it.

It doesn't matter that when the save/open dialog appear what I choose (even closing with the X) the formating functionality is gone. But if I just triggering the normal CTRL+S / +O dialogs that not causing anything like that.

It seems like even I can select texts but the ME can't apply anything or can't see the selected text.

Have any idea how could I debug this?

(If the browser is set to auto download so no popup window the script works fine, so it looks like the ME somehow loosing focus...)

I tried to save the DIV content in a variable before save and after inserting back and reapply the ME scipts but it had the same result.

Thx.

**Comment by j0k3r** [comment] 2015-06-04 07:16
It seems hard to me to know where the problem can be in MediumEditor.
If it's not too complicated, could you provide a jsfiddle that reproduce the bug?

**Comment by kardazs** [comment] 2015-06-11 23:03
Yes I will create a fiddle and provide the link during the day, thx for the response.

**Comment by nmielnik** [comment] 2015-08-09 15:32
@kardazs and update on this issue?

**Comment by sathyanpry** [comment] 2015-08-17 06:54
I too face the same issue. Any one have any solution to this issue?? I am using FF 34.0.


    the toolbar appears
    it is detecting that the selected text already has formating (eg. bold or italic)
    the anchor popup appears if I clicking on the toolbar

But no format applied on the text.

Any ideas whats happening here..

**Comment by nmielnik** [comment] 2015-09-12 16:37
@sathyanpry are you also using FileSaveJS when you see this issue?  Or are you seeing the issue in a different environment/scenario?

If anyone can provide a jsfiddle with the issue reproducing, we'll be happy to take a look.  Without that, there seems to be a lot of use-case specific things that will make it hard to diagnose what could be happening.  Even more details as to exactly what frameworks are on the page could help. I'm not familiar with FileSaverJS so I don't have much of a guess here.

**Comment by j0k3r** [comment] 2016-05-03 07:48
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Closed by j0k3r** 2016-05-03 07:48 UTC
Labels: awaiting response
