### ISSUE TITLE
Custom buttons not compatible with use of textarea?

### ISSUE THREAD

**Issue by ikoene** [yabwe/medium-editor#968] opened 2016-02-11 12:35 UTC
Recently I started working with MediumEditor. Kudos for the excellent docs btw. I wanted to make a custom button, so like most people, I followed the [tutorial](https://github.com/yabwe/medium-editor/blob/master/src/js/extensions/WALKTHROUGH-BUTTON.md). It works like a charm, but when saving my form, the `<mark>` tags were not saved. It was as if I never placed them. Only the default buttons were saved. After some research, I read the following in the documentation:

> MediumEditor also supports textarea. If you provide a textarea element, the script will create a new div with contentEditable=true, hide the textarea and link the textarea value to the div HTML content.

When I learned about the hidden textarea, I made it visible and I noticed that the custom button was not populating the hidden textarea. Can someone explain to me why this is? In the tutorial, there's no info about this... Is this a bug, or am I doing something terribly wrong?

````
    var HighlighterButton = MediumEditor.extensions.button.extend({
        name: 'highlighter',
        contentFA: '<i class="fa fa-paint-brush"></i>',
        aria: 'hightlight',
        init: function () {
            MediumEditor.extensions.button.prototype.init.call(this);
            this.classApplier = rangy.createClassApplier('highlight', {
                elementTagName: 'mark',
                normalize: true
            });
        },
        handleClick: function (event) {
            this.classApplier.toggleSelection();
            $(this.button).toggleClass('medium-editor-button-active');
        },
        isAlreadyApplied: function (node) {
            return ($.inArray('highlight', node.classList) !== -1);
        }
    });
````

Creating a MediumEditor instance on a `<div>` element on the other hand, does not have this issue (because it's not using a hidden DOM element of course). In my case, that solved it.

**Comment by nmielnik** [comment] 2016-02-11 14:09
@ikoene this is actually a duplicate of #942 , I've outlined what could be added to fix the demo. If you're interested and had a chance to verify the fix we'd be happy to take a PR to fix it :wink:

**Closed by nmielnik** 2016-02-11 14:10 UTC
