### ISSUE TITLE
placeholder text is still visible after assigning content to innerHTML

### ISSUE THREAD

**Issue by makoConstruct** [yabwe/medium-editor#194] opened 2014-03-31 21:44 UTC
Could probably be fixed with an :empty psuedoelement or a sibling selector or something. I tried sticking an :empty between .medium-editor-placeholde and :after and it suppressed the placeholder in all cases so that didn't work. Maybe I was just doing it wrong or something idk.

**Comment by ebengtso** [comment] 2015-08-09 13:29
i'm using the function setContent and it, in my opnion, should call
yourElement.classList.remove('medium-editor-placeholder')

**Comment by nmielnik** [comment] 2015-08-10 13:47
@ebengtso would you open an issue about this?

I agree that setting the content should trigger the placeholder to go away, but we'll have to think a bit about the way to implement it.  We wouldn't want the `setContent` method to remove the placeholder attribute directly, since the placeholder logic is in it's own extension and we want to make sure we keep separation of concerns.  We'll just need to change around the placeholder extension a bit to know whenever the content changes.

**Comment by nmielnik** [comment] 2015-08-19 23:54
For those of you who are manually setting `innerHTML` on the editor element, you should instead use the [setContent(html, index)](https://github.com/yabwe/medium-editor/blob/master/API.md#setcontenthtml-index) method of the editor itself:

```js
var editor = new MediumEditor('.editable');
editor.setContent('Content For 1st Element', 0);
editor.setContent('Content for 2nd Element', 1);
```

A fix is coming which will ensure the placeholder is hidden when calling `setContent()` so the issue will ultimately be resolved.  Closing this issue as a duplicate of #768 , which will be fixed soon.

**Closed by nmielnik** 2015-08-19 23:54 UTC
Labels: easy first bug, enhancement
