### ISSUE TITLE
Error when edit link

### ISSUE THREAD

**Issue by fkroockmann** [yabwe/medium-editor#1137] opened 2016-07-08 08:47 UTC
Hello,

I use your library and she is awesome :) but when i want to edit a link i have a javascript error:

`app.js:45928 Uncaught TypeError: Array.prototype.forEach called on null or undefined`

[Description of the bug or feature]

### Steps to reproduce

1 - Create a link
2 - hover on the link

I test it on your demo and i have this error too (https://yabwe.github.io/medium-editor/)

### Versions

- medium-editor: all
- browser: chrome
- OS:

Thanks

**Comment by nmielnik** [comment] 2016-07-08 13:52
@fkroockmann I'm not able to reproduce this on the demo page in chrome:

1. Highlight a chunk of text
2. In the toolbar, click the link button
3. Type a valid url in the textbox (http://www.google.com)
4. Click the check mark, which closes the dialog and converts the highlighted text to a link
5. Click outside of the editor so the toolbar goes away
6. Run my mouse cursor over top of the link, and see the anchor-preview appears and displays "http://www.google.com"
7. Click the link, the toolbar re-appears with the anchor editor textbox pre-filled with "http://www.google.com"
8. I changed the link to something else and click the checkbox
9. The link changes and there are no errors in the console.

Perhaps you could give more detailed repro steps to describe how you're seeing this error?

**Comment by fkroockmann** [comment] 2016-07-08 14:00
Thanks for answer @nmielnik 

I reproduce it with an invalid url like "toto", can you test with that, i succeed again on demo

**Comment by nmielnik** [comment] 2016-07-08 14:05
I went to the demo page and typed in an invalid url instead of google (ie "toto") and i was still able to create the link, hover it, and edit it to something else.  I tried highlight different words in the demo and still wasn't able to reproduce.  Can you provide a screencast or step-by-step directions on what you're doing when you see this?

**Comment by rishijain** [comment] 2016-07-08 21:06
I think I got how to repro it. I am jumping directly to step 6 (after taking first 5 steps mentioned by @nmielnik )

Steps:
6. Double click on the text and the toolbar appears. Just hover over the link button and the error occurs. 
Error occurs on hovering, it may feel like it happens when you click on the link button. 

To be specific, it happens in `detachDOMEvent` function on line `2480` in `dist/js/medium-editor.js` file

Also @fkroockmann if you want to edit the existing link, you can just hover over the text and the anchor-preview appears and you can click on it and change the link, as mentioned by @nmielnik in his steps. It works just fine. Just saying if you are stuck at this and not able to edit links right now.

**Comment by fkroockmann** [comment] 2016-07-08 21:34
Ok, i can edit, im not stuck but an error occurs.

Thanks @rishijain

**Comment by nmielnik** [comment] 2016-07-24 05:55
I was able to get this to reproduce by following the steps outlined in #1151 

I was able to briefly describe what needs to be fixed for this as well, so I'm closing this as a duplicate of #1151 (even though 1151 was opened after this one).

Thanks @fkroockmann !

**Closed by nmielnik** 2016-07-24 05:55 UTC
Labels: bug
