### ISSUE TITLE
Add paragraph IDs?

### ISSUE THREAD

**Issue by nicholasalanbrown** [yabwe/medium-editor#842] opened 2015-10-13 03:05 UTC
This is a terrific library with a very extensive readme, but I'm struggling to figure out how I can have the editor create paragraph IDs any time the user creates a new paragraph. I tried handling this after the submit action by replacing ```<p>``` tags with unique IDs a la ```<p id="1234">``` and that works fine, but if I edit the markup again with the editor and create a new paragraph it simply copies down the unique ID from above.

I'm trying to get something like SideComments working and this is a key part. Any help would be much appreciated!

**Comment by nmielnik** [comment] 2015-10-14 12:59
Hey @nicholasalanbrown , I believe what you're seeing is a duplicate of #764.  I moved your comment over to that issue and I'll comment through there.

**Closed by nmielnik** 2015-10-14 12:59 UTC
