### ISSUE TITLE
Completeness and intention of blockContainerElementNames

### ISSUE THREAD

**Issue by csarven** [yabwe/medium-editor#808] opened 2015-09-11 12:36 UTC
Currently we have this:

```
blockContainerElementNames: [
    // elements our editor generates
    'p', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'blockquote', 'pre', 'ul', 'li', 'ol',
    // all other known block elements
    'address', 'article', 'aside', 'audio', 'canvas', 'dd', 'dl', 'dt', 'fieldset',
    'figcaption', 'figure', 'footer', 'form', 'header', 'hgroup', 'main', 'nav',
    'noscript', 'output', 'section', 'table', 'tbody', 'tfoot', 'video'
]
```

That is not a complete list of block level elements e.g., `p`, `div`.

Should this array be the complete list of block level elements or is there a particular semantics in context of ME that's outside of the well-known list of block level elements. See also: https://developer.mozilla.org/en/docs/Web/HTML/Block-level_elements

**Comment by nmielnik** [comment] 2015-09-11 13:26
The only element missing from the list is `div` (`p` is the first one in the list) and this was done intentionally at one point, since the outer container of the editor will always be a div.  We would have to understand what kind of problems not having `div` in the list is causing if we were going to try to fix anything.

**Comment by csarven** [comment] 2015-09-11 13:32
Oops, totally skipped over `p`, thanks.

As I understand it, the situation is the other way around as the example with `section` in #809 tries to explain. Basically, if `section` is on the list (and as it should be), then things like execFormatBlock should work. Adding `div` into that list may/will break things that's working with `isBlockContainer`

**Comment by nmielnik** [comment] 2015-09-12 16:05
If I understand this correctly, I think the issue is more specifically around `execFormatBlock` and whether it should even be using `blockContainerElementNames`.  Currently, I think the `blockContainerElementNames` are ok as is, but may possibly need to be renamed.

Closing this issue as #809 will address the root issue.

**Closed by nmielnik** 2015-09-12 16:05 UTC

**Comment by csarven** [comment] 2015-09-12 17:09
Closing this issue is fine if the semantics of `blockContainerElementNames` implies that "the outer container of the editor will always be a div". IMO, this is not always the case nor should be forced. I would also suggest if that interpretation is not well-known some documentation on that would help.
