### ISSUE TITLE
NS_ERROR_FAILURE in Firefox for every keystroke in Custom Element

### ISSUE THREAD

**Issue by csuwildcat** [yabwe/medium-editor#1000] opened 2016-03-05 15:53 UTC
I have wrapped Medium Editor in a generic Web Component Custom Element (`<x-medium-editor>` is the node the editor is instantiated on) which somehow causes Firefox to throw an error every time the user enters text. When pressing enter, the entire outerHTML is duplicated resulting in a copy of the editor element itself. Here's the code point flagged in dev tools:

```javascript
if (MediumEditor.util.isMediumEditorElement(node) && node.children.length === 0) {
  this.options.ownerDocument.execCommand('formatBlock', false, 'p');
} 
```

**Comment by nmielnik** [comment] 2016-03-08 02:50
First @csuwildcat congrats on owning issue #1000 .

So, I've run into this issue quite a few times with firefox.  Generally, when I've gotten the dubious `NS_ERROR_FAILURE` when calling `execCommand()` it has been when focus and/or selection has not been set properly.  Basically, trying to call `document.execCommand()` if the focus/selection is not properly set within a `contenteditable` element in firefox often gives this error.

If you were able to narrow it down to this line, could you debug and just call `document.getSelection()` to make sure the selection and focus is within the right element?

**Comment by NickBlow** [comment] 2016-04-04 10:44
I have the same issue - I called document.getSelection() and the focus was definitely in the right element. 

The error only started for me when I pressed enter in the text box and then every key stroke from then on generated an error. 

The lines of code that caused the error for me were, but it was browserified and uglified so it's a bit hard to pin down: 
 
`this.relativeContainer.appendChild(this.getToolbarElement()):this.getEditorOption("elementsContainer").appendChild(this.getToolbarElement());`

**Comment by nmielnik** [comment] 2016-04-16 21:49
This may have been a duplicate of #994 , and thus could have been fixed by #1052 (and available starting with version 5.16.1 of medium-editor)

@NickBlow or @csuwildcat could you test out the newest version of medium-editor and see if this issue has been resolved for you?

**Closed by nmielnik** 2016-04-16 21:49 UTC
Labels: browser-firefox, bug

**Comment by josefromsanjose** [comment] 2016-08-26 17:54
I get this issue when using the editor with Angular. Error happens only when using the ordered list and unordered list buttons side the function function `execActionInternal(action, opts) {}`. Does anyone have a solution for this, specifically with Angular. The error does not happen without the framework.

**Comment by mrsweaters** [comment] 2017-11-16 21:36
I'm experiencing this issue with medium-editor 5.23.2 and Angular 1.6.6.

**Comment by mrsweaters** [comment] 2017-11-16 22:14
Ah okay, so it appears that my issue is that my editor is on a `div` but is not being recognized as a block level element by the editor:
https://github.com/yabwe/medium-editor/blob/c619e756c0c8dda7bbb587b6b97209d984c208e8/src/js/util.js#L109

Is there a reason, why `div` is not in this list?
