### ISSUE TITLE
Sometimes adding class to links , doesn't work

### ISSUE THREAD

**Issue by l2aelba** [yabwe/medium-editor#738] opened 2015-07-22 11:54 UTC
Demo : http://jsfiddle.net/8jrod5c9/

![a3aebhtxxh](https://cloud.githubusercontent.com/assets/983458/8824755/0807eb6a-3079-11e5-924d-fd009cf690cf.gif)
Found bugs :
- Button checkbox still checked
- Sometimes adding class does not work (work perfect just first time)
- You can see more on GIF

**Comment by nmielnik** [comment] 2015-07-22 13:59
Yeah, there are a bunch of things going wrong here.  I've checked in a fix for the css so the toolbar doesn't look so horrific with checkboxes in it.

Figuring out why things aren't working properly, that will take some investigation.

**Comment by nmielnik** [comment] 2015-07-28 04:58
@l2aelba I've updated your jsfiddle to include the latest version of MediumEditor: http://jsfiddle.net/8jrod5c9/3/ a long with a few minor tweaks.

1. The issue where the checkboxes are showing up looking terrible in the toolbar has been fixed as of https://github.com/yabwe/medium-editor/commit/d40c6ed9bdb55df9b1ca9e9344d95008f1d121f0 and was released in version 5.5.1
1. I've opened #747 to make sure the checkboxes in the toolbar checked/unchecked correctly based on the anchor you're editing

I also discovered that there's a weird side-effect caused by your `.button` class having a `padding: 10px`.  Because of this padding, if you create a button link, and then un-link it, you are left with a single character of black-background text directly before the link.  Removing the padding from that button makes the issue go away, I removed that padding in the updated jsfiddle link.

Regarding the other problem you ran into in your repo gif, where you're unable to create a 2nd link.  It seems like it's limited to just when you:
1. Create a button link
2. Hit <kbd>ENTER</kbd> a few times to insert some line breaks
3. Start typing text directly after the line breaks, and attempt to create a link with that text.

If you insert any other character (other than new lines) between the previous link and the new link you're trying to create, the issue doesn't happen and the new link is created correctly.

I believe the issue may be related to when ONLY line-breaks separate a new link you're trying to create and a previously created link.  Let me know if you're able to reproduce it another way.

Hopefully now this scopes down the severity of the issue a bit.

**Comment by l2aelba** [comment] 2015-07-28 07:20
@nmielnik Thanks , i tested https://github.com/yabwe/medium-editor/pull/747

Checkboxes (checked, unchecked) are work.

Now just about addling 2nd link (class/link) left :D

**Comment by nmielnik** [comment] 2015-07-29 14:01
Correct: This will not be fixed by PR #752, but I have found the cause of the issue and I'll work on trying to get the fix in

**Comment by patrick-webs** [comment] 2015-07-29 15:40
![screen shot 2015-07-29 at 11 38 22 am-fs8](https://cloud.githubusercontent.com/assets/10403580/8962024/767f7c8a-35e6-11e5-9030-106fb9a794f5.png)
we may be able to fix this by just removing the `range.collapse(true);` , but need to check and see if the range will still be collapsed in the cases where this was intended (restoration of a collapsed cursor at the end of a string of empty paragraphs).

**Comment by l2aelba** [comment] 2015-07-30 07:10
I waiting for marge :D Thanks all guys

**Closed** 2015-08-02 08:56 UTC
Labels: bug
