### ISSUE TITLE
Pasting does not trigger editablePaste

### ISSUE THREAD

**Issue by JeanCarriere** [yabwe/medium-editor#1098] opened 2016-05-24 12:42 UTC
### Description
Copy and pasting a file in the editor does not trigger editablePaste event

### Steps to reproduce

1. Subscribe to the editablePaste event
2. Copy a file to the clipboard
3. Paste in the editor with CTL V

**Expected behavior:**  
The subscribed function should be called

**Actual behavior:** 
It's not called
There is an error in the console : 
Uncaught TypeError: Cannot read property 'split' of undefined
a.Extension.extend.doPaste	@	medium-editor.min.js:3

### Versions

- medium-editor: 5.18.0
- browser: Chrome 50
- OS: OS X El Capitan

**Comment by j0k3r** [comment] 2016-05-24 14:21
Which kind of file are your dropping in the editor, an image, a text file?

**Comment by JeanCarriere** [comment] 2016-05-24 14:35
For instance, I paste a picture copied in the clipboard from a web page.
The problem seems to come from the handlePasteBinPaste mechanism.

**Comment by j0k3r** [comment] 2016-05-24 21:51
Didn't took time to look at it, but we rewrote the pasting part recently, it might be related.

**Comment by nmielnik** [comment] 2016-05-25 18:36
This is definitely a result of the new code.  Right click paste fires the event correctly, but keyboard paste does not.  This is because when we capture the <kbd>CTRL</kbd> + <kbd>V</kbd> command, we call preventDefault, which will prevent the actual paste event from ever triggering.  Since that event doesn't trigger, our handler which fires the `editablePaste` event never gets triggered.

I can get a fix for this in soon, thanks a ton for point this out @JeanCarriere !

**Comment by nmielnik** [comment] 2016-05-26 05:23
@JeanCarriere the fix for this is ready (#1099), as soon as it's merged in we'll cut a new patch release so you'll have the fix available.  Thanks again for pointing out this issue.

**Comment by nmielnik** [comment] 2016-05-26 14:55
@JeanCarriere for the case where you weren't able to copy and paste an image in, I wasn't able to reproduce it...what options are you passing when you initialize medium-editor?  There are some [paste related options](https://github.com/yabwe/medium-editor#paste-options) you'll have to configure to ensure the images will show up  Are you setting `paste. forcePlainText` to false or `paste. cleanPastedHTML` to true?

**Closed** 2016-05-27 13:56 UTC
Labels: bug, paste problem

**Comment by JeanCarriere** [comment] 2016-05-27 14:39
The options I have are : 

- forcePlainText : true
- cleanPastedHTML : false

**Comment by nmielnik** [comment] 2016-05-27 14:54
In order for the html to come through (and for images to not be ignored), you'll need to set `forcePlainText: false`.
