### ISSUE TITLE
Use <h1> instead of <p> as a default wrapper?

### ISSUE THREAD

**Issue by IljaDaderko** [yabwe/medium-editor#1006] opened 2016-03-10 15:00 UTC
I need to figure out a way to use `<h1>` as default wrapper tag instead of `<p>` so far I wasn't able to find any option for this.

**Comment by nmielnik** [comment] 2016-03-20 16:11
So the part of the code that automatically wraps text with a `<p>` has been brought up in a bunch of issues ( #907, #829, #865, #149 ) and is potentially being modified by #997 (thanks @harzzn)

If someone wanted to try adding support for this into the editor, you could try just modifying the `handleKeyUp()` method in [core.js](https://github.com/yabwe/medium-editor/blob/master/src/js/core.js).  In particular, the lines that do this:
```js
this.options.ownerDocument.execCommand('formatBlock', false, 'p');
```
Changing the 'p' passed to `execCommand` to be a tag name that is passed in via an option might be all that is needed, but it would take some experimentation to see how it all behaves and if there are any weird issues that come up.

**Comment by nmielnik** [comment] 2016-03-20 17:20
It looks like this is actually just a duplicate of #319 , so I'm closing this issue and moving my comment over there.

**Closed by nmielnik** 2016-03-20 17:20 UTC
Labels: enhancement
