### ISSUE TITLE
Return key doesn't work at the end of an area with bad formatting

### ISSUE THREAD

**Issue by nkalush** [yabwe/medium-editor#788] opened 2015-08-21 22:10 UTC
So I have some content that was imported from an older cms and it's got some br tags and paragraphs that aren't wrapped in p tags, nothing too terrible, but it breaks medium-editor when the `disableDoubleReturn` flag is true.

Here is an example, if you try to add a new line after the last paragraph it doesn't work:
http://jsfiddle.net/8o7coLkq/

**Comment by rishijain** [comment] 2015-10-19 17:21
Hi @nmielnik , I could reproduce this issue at dev environment and have also fixed the issue. But could not put together a passing test case for it. 

Can you have a look at what I am doing wrong in the test cases? https://github.com/joshsoftware/medium-editor/commit/6f5a8531791184dcf139bcb1ebf300d4fd27e207

I have added 2 test cases, first for the issue filed above i.e placing cursor at the end of the last paragraph.
Second I have added a test case for placing cursor at start of the last paragraph and then pressing enter.

**Comment by nmielnik** [comment] 2015-10-30 15:01
@rishijain apologies for not seeing this, I'm not sure how I missed this in my email.

Looks like you figured it out though, thanks a ton for getting through and finding a fix!

**Comment by nmielnik** [comment] 2015-10-30 15:02
Fixed via #862

**Closed by nmielnik** 2015-10-30 15:02 UTC
Labels: bug

**Comment by rishijain** [comment] 2015-11-01 09:35
@nmielnik Not a  problem.
