### ISSUE TITLE
Can't disable keyboardCommands

### ISSUE THREAD

**Issue by renarsvilnis** [yabwe/medium-editor#1079] opened 2016-05-06 23:35 UTC
### Can't disable `keyboardCommands`

Unable to disable `keyboardCommands` for an `MediumEditor` instance.

### Steps to reproduce

1. Create the instance as following (*as suggested by the [documentation](https://github.com/yabwe/medium-editor#keyboardcommands-options)*):

   ```javascript
   const el = document.getElementById('text-editor');
   const editor = new MediumEditor(el, {
     keyboardCommands: false
   });
   ```
2. Open up the page and add some text in the editor.
3. Try to bold the text by doing a keyboard shortcut, in my case `cmd` + `b` 

**Expected behavior:** Nothing

**Actual behavior:** Text becomes bold

**Link to an example:** http://codepen.io/renarsvilnis/pen/WwPQNO

### Versions

- medium-editor: 5.16.1
- browser: Google Chrome 50.0.2661.94 (64-bit) 
- OS: OSX

> Also tried on different browsers with no result.

### Notes
Have tried also passing different of configs with no luck:

```javascript
const config = {
  keyboardCommands: {}
};
```

```javascript
const config = {
  keyboardCommands: {
    commands: [],
  }
};
```

**Comment by j0k3r** [comment] 2016-05-07 07:37
The problem is related on how Chrome handle contenteditable. By default, they handle all shortcut like bold and italic.
We introduced `keyboardCommands` because other browser doesn't handle shortcut by default, like Firefox.

So we you disable `keyboardCommands`, it just disable our internal handle for shortcut. We didn't disable browser behavior.

Give a try on Firefox and you'll see that shortcut doesn't work.

This can be an easy bug thought. When `keyboardCommands`, disable all our internal handle to that it catch the shortcut but do nothing.

**Comment by nmielnik** [comment] 2016-05-09 15:26
@renarsvilnis looking at the code I think there's a workaround you could use to prevent the default keyboard shortcuts until the extension is modified to more cleanly support the behavior you're describing.

You can pass in no-op functions as handlers for the commands in the `keyboardCommands` extension, this will kill the event and then try to execute the handler code, which would do nothing (since it's a no-op).

```js
const config = {
  keyboardCommands: {
    commands: [
      { 
        command: function () {},
        key: 'B',
        meta: true,
        shift: false,
        alt: false 
      }, {
        command: function () {},
        key: 'I',
        meta: true,
        shift: false,
        alt: false 
      }, {
        command: function () {},
        key: 'U',
        meta: true,
        shift: false,
        alt: false 
      }
    ]
  }
};
```

**Comment by nmielnik** [comment] 2016-05-09 15:30
Closing this as it seems to be a duplicate of #903

**Closed by nmielnik** 2016-05-09 15:30 UTC
Labels: easy first bug
