### ISSUE TITLE
triggering focus() via editor.selectElement()

### ISSUE THREAD

**Issue by jessegilbert** [yabwe/medium-editor#850] opened 2015-10-19 08:47 UTC
My goal is to programmatically trigger a focus() event to allow the user to begin typing into an instance of MediumEditor without having to click.  I gather from reading other issue reports that the recommended method is to call editor.selectElement( element ).

In using this I'm noticing that the onFocus() event handler is being properly called, but this is not resulting in an active cursor in the editor.  I still have to click into the editable field order to get an active cursor, regardless of whether the editor has existing text or not.

Any ideas of how I might accomplish what I'm after?  I've searched through the related issues and didn't see a comparable question.

The relevant settings of this instance of MediumEditor:

	noteEdit = new MediumEditor( '.note',
		{
			placeholder: {
				text: ''
			},
			toolbar: {
				buttons: ['bold', 'italic', 'underline', 'indent', 'outdent', 'unorderedlist']
			},
			paste: {
				cleanPastedHTML: true
			},
			imageDragging: false
		}
	);

**Comment by nmielnik** [comment] 2015-10-19 15:48
How are you calling `selectElement()`?

You'll want to make sure you pass in the element with the `.note` class on it as the argument to `selectElement()`.

```js
var noteEdit = new MediumEditor('.note', {
   // your options
});

noteEdit.selectElement(document.querySelector('.note'));
```

**Comment by jessegilbert** [comment] 2015-10-19 16:12
Yes, that's exactly how I'm calling it.  I can confirm that I'm targeting the right element because I have a custom event handler that is attached to the instance of MediumEditor as follows:

	noteEdit.subscribe('focus', processFocus );

The processFocus() method is executed, but the issue may be that I am adding DOM elements dynamically here -  a new DIV, a few buttons and some custom event handlers for them.

When I click into the MediumEditor instance the processFocus() method executes, the DOM elements are added and the cursor is active in the editor.  When I call selectElement() the DOM elements are added but the cursor is not active.

**Comment by nmielnik** [comment] 2015-10-19 17:31
So you can see that the code will ultimately call `.focus()` on the element itself (see code [here](https://github.com/yabwe/medium-editor/blob/master/src/js/events.js#L311))...

I would try just setting focus to the editable element manually at any point (`document.querySelector('.note').focus()`).  If that actually puts focus inside of the element, but the calls from the medium-editor code to set focus aren't working when you call them, perhaps it could be some sort of timing issue?  Have you tried calling `.selectElement()` just from the web-console of your application to see if it works on its own?

**Comment by jessegilbert** [comment] 2015-10-20 04:09
Yes, I've tried setting focus manually as well -  same results.

As a test, I commented the line containing noteEditor.subscribe('focus'), and the call to selectElement() worked as desired, once.  On subsequent tests I had the same problem.

I've tried delaying calls using setTimeout() to:

editor.selectElement(element)
element.focus()
element.click()

All of these cause the focus handler to trigger, but the cursor is not active.  

If I place default text into the field by setting element.innerHTML the text is highlighted and toolbar is active, but even then I can't simply type into the MediumEditor -  I have to click into the field.  There's likely something going on with execution order but I can't figure it out.

**Comment by nmielnik** [comment] 2015-10-29 12:56
@jessegilbert if you can get this to reproduce in a jsfiddle or codepen, I could try to take a look.  I'm guessing there's some other thing at play here and I'm about out of guesses :confused:

**Comment by TCUguy** [comment] 2016-01-04 17:58
Has this been resolved by any chance? also looking for an answer

**Comment by nmielnik** [comment] 2016-02-22 03:49
@TCUguy / @jessegilbert  can you provide a jsfiddle / codepen / jsbin where you're able to reproduce this?

**Comment by kadishmal** [comment] 2016-03-02 10:25
The following has worked for me:

    editor.selectElement(this.refs.editor.childNodes[0])

... where `this.refs.editor` is a reference to the DOM element of the editor. What the above does is focuses on the first child element of the editor, which is always `<p>` in my case.

**Closed** 2016-05-22 02:57 UTC
Labels: question

**Comment by webmobiledev** [comment] 2020-12-03 02:58
`this.editor.selectElement(document.querySelector('.medium-editor-element'))` works for me.
