### ISSUE TITLE
Underline,Italic, Bold repeating paragraph properties on enter

### ISSUE THREAD

**Issue by ankur0890** [yabwe/medium-editor#1076] opened 2016-05-03 07:38 UTC
Inline formatting options repeating paragraph properties on enter click.

Steps to reproduce:
1. Type paragraph
2. Edit html and assign some data-property on the fly.
3. Press enter.
4. It will repeat the old paragraphs property in the new one. 

Expected: New paragraph without repeating the properties on enter

<img width="1005" alt="screen shot 2016-05-03 at 1 07 56 pm" src="https://cloud.githubusercontent.com/assets/1263424/14977252/19ede530-1130-11e6-946c-ef7d28d5b8e3.png">

**Comment by j0k3r** [comment] 2016-05-03 07:46
As far as I remember (I can't find the associated issue where we already talked about that) this is a _bug_ in contenteditable which kind of duplicate the previous paragraph with all affected properties when you hit enter and create a new paragraph.

**Comment by nmielnik** [comment] 2016-05-04 01:02
@j0k3r the issue you were looking for was #764 .  Closing this as a duplicate of that.

**Closed by nmielnik** 2016-05-04 01:02 UTC
