### ISSUE TITLE
keyboardCommands restricting not working

### ISSUE THREAD

**Issue by ramgp** [yabwe/medium-editor#1116] opened 2016-06-06 23:27 UTC
### Description

When restricting the **`keyboardCommands`** all of the other default options still produce their desired default action. e.g. with the following config pressing Ctrl+U still produces the underline styling of the current selection.

```
        keyboardCommands: {
            commands: [
              {
                command: "bold",
                key: "B",
                meta: true,
                shift: false,
                alt: false
              },
              {
                command: 'italic',
                key: 'I',
                meta: true,
                shift: false,
                alt: false
              }
            ]
          }
```

**Expected behavior:** Only the configured subset of keyboard commands should be allowed based on the config options
**Actual behavior:** The commands are executed and accepted regardless of the configuration that the medium editor is created with. Even using different key combination results in both the default key combination as well as the custom one producing the action.

So maybe the question is: Is restricting the available or allowed actions possible?

### Versions

- medium-editor: 5.20
- browser: Chrome 51
- OS: NA

**Comment by nmielnik** [comment] 2016-06-08 05:47
@ramgp you can find how to work around this in #903 (this is a duplicate of that). 

The default keyboard shortcuts are implemented by the browsers themselves, so our implementation requires you actually disable the keyboard shortcuts explicitly

**Closed by nmielnik** 2016-06-08 05:47 UTC
