### ISSUE TITLE
Focus cursor on end of box

### ISSUE THREAD

**Issue by bugcafe** [yabwe/medium-editor#998] opened 2016-03-05 00:12 UTC
Is there a way to set the caret to the end of the medium-editor box (using jQuery)?

eg. 
I have a line of code that looks like this:
  $(this).parent().parent().prev().prev().children().children(".editable").focus();

which sets the focus on the medium-editor box, but the cursor is at the start of the box. when there is some text already in the box, I want to be able to put the cursor at the end of the box

is this possible with medium-editor?

It doesn't appear to be a text input box so the usual methods don't seem to work.

**Comment by nmielnik** [comment] 2016-03-05 19:20
@bugcafe please see #730 for some discussion on this.  (I'll close this issue for now as I think it might be a duplicate of that).

@dominicwong617 provided this gist as some sample code that could accomplish what I think you're looking for:  https://gist.github.com/dominicwong617/d9f4188b4d364d052b45#file-medium_editor_caret-js-coffee

**Closed by nmielnik** 2016-03-05 19:20 UTC
