### ISSUE TITLE
Possible to disable something in children ?

### ISSUE THREAD

**Issue by l2aelba** [yabwe/medium-editor#694] opened 2015-06-18 12:24 UTC
Something like this..

``` html
<div class="editable">
    <h2>Lorem ipsum dolor sit amet</h2>
    <p>Id mea habeo harum omittantur</p>
    <p data-disable-editing></p>
    <a href="#" data-disable-editing data-disable-toolbar>link</a>
    <p data-disable-returng>One line only</p>
</div>
````

Was wondering how can I do that ?

**Comment by j0k3r** [comment] 2015-06-18 13:16
Do you want to disable them using the toolbar? Or do you want them _by default_ when you create a new content, for example?

Because if you define a node with attribute `contenteditable="false"` you won't be able to edit them after. Maybe that's what you are looking for.

**Comment by nmielnik** [comment] 2015-06-18 13:54
Yeah, like @j0k3r said, using `<p contenteditable="false">One line only</p>` or `<a contenteditable="false"></a>` will make that piece of text uneditable.

Also, we don't currently support disabling the toolbar for specific elements within the editable element, we only allow disabling the toolbar for the outer editable `<div>` that contains everything...but this could be an interesting feature to add if you have a need for it.

**Comment by l2aelba** [comment] 2015-06-19 08:12
Im using `contenteditable="false"` too, but not so perfect like... toolbar will come sometimes

**Comment by nmielnik** [comment] 2015-06-19 12:56
Any interest in trying to add the feature yourself?  Since you have a use case for it, it seems like a good way to try to contribute and help us out!

**Comment by nmielnik** [comment] 2015-07-02 22:10
Looks like this is actually a duplicate of #180

**Closed by nmielnik** 2015-07-02 22:10 UTC
Labels: enhancement
