### ISSUE TITLE
"Enter" - Can I change it's behavior?

### ISSUE THREAD

**Issue by nzifnab** [yabwe/medium-editor#704] opened 2015-06-25 17:54 UTC
I did see #333 

I may be a little late here but... in Word if you want a new line you just hit "enter"... If you need a new paragraph you hit "enter tab" or "enter enter" (depending what kind of paragraph you want). All Word understands is "new lines" when you hit enter.

The problem with using the `<p>` tag every time I hit enter in the editor is that the `<p>` tag is styled to have margin. This isn't specifically a problem for enter itself, but when I have a contenteditable field that currently *only* has text in it, and then I change anything in there, it wraps the whole thing in a `<p>` which suddenly shifts the page around slightly because now it's adding margin where before there wasn't any. This is a little jarring for the user and makes the layout look a little weird.

Is there a way to just change "enter" to insert `<br>`'s instead? I'm giving non-techies the ability to edit content on their documents, and they don't care one way or the other if it's using a paragraph tag or a newline tag - all they expect is that hitting enter twice will give them extra space, and hitting enter once will not.... Which is exactly how OpenOffice, Google Docs, and Microsoft Word works.

Edit: I made a jsfiddle that highlights a specific concern of mine: https://jsfiddle.net/nzifnab/2ov4eqkw/4/

If you focus the first field, and do nothing EXCEPT hit "tab" to go to the second field, suddenly the second table row gets shifted down due to that extra `<p>` being added. If I didn't have to worry about any new extra `<p>` tags, and `<br>` was the mechanism for "enter", then this wouldn't be a problem, and it'd be more intuitive for our users when editing content.

**Comment by nmielnik** [comment] 2015-06-26 15:37
So one way we've worked around this issue for our application is to not fight the fact that contenteditable will always want to have things inside of a `<p>`.  For our app, we just always have the content wrapped in a `<p>` tag such that a new one won't automatically get added by the browsers.

So the starting state of our text (if it's empty) is to just have `<p><br /></p>` instead of an empty string.  It's not ideal, but the browsers seem to align in supporting this.

**Comment by nmielnik** [comment] 2015-07-25 21:10
This is a duplicate of #70 so closing this issue and linking

**Closed by nmielnik** 2015-07-25 21:10 UTC
Labels: awaiting response, question
