### ISSUE TITLE
Ability to disallow certain styles (i.e. bold / italic / underline) on h2 and h1 tags

### ISSUE THREAD

**Issue by IljaDaderko** [yabwe/medium-editor#1015] opened 2016-03-21 16:38 UTC
To provide some consistency within article builder that I am working on I would like to limit users to not be able and apply certain styling to text that was given H1 or H2 styling in other words wrapped in respective tags. Is there a way to, for example, return nothing when users try to make H1 bold / italic or underlined? They should only be able to change it back to paragraph text so they can afterwards apply those styles.

**Comment by nmielnik** [comment] 2016-03-24 03:17
This may be a duplicate of #797 but I'd like to make sure before I close the issue. Can you check that issue and verify if it's the same as what you're describing?

I believe @davideanderson was attempting to implement an extension that would modify which buttons appear in the toolbar based on what type of text was being highlighted.  For example, whenever the cursor is inside a header tag (`<h1>`, `<h2>`, etc.), don't show bold/italic/underline buttons.

I'm not sure how ready his code is for distribution ( @davideanderson might be able to clarify) but you can find the code in his repo [here](https://github.com/davideanderson/medium-editor-toolbar-states) along with a simple [demo](http://davideanderson.github.io/medium-editor-toolbar-states/).

If this is what you're looking for, you could try using his code or building your own extension as a variation of this.  Does this answer your question?

**Comment by j0k3r** [comment] 2016-05-03 07:58
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.

**Closed by j0k3r** 2016-05-03 07:58 UTC
Labels: awaiting response, question
