### ISSUE TITLE
Whitelist elements

### ISSUE THREAD

**Issue by martijndekuijper** [yabwe/medium-editor#1149] opened 2016-07-18 14:14 UTC
I would really, really love to have the ability to whitelist elements instead of using the cleanTags option. Right now I only want people to just be able to paste stuff that is in the toolbar (bold, italic, links). Any progress here?

**Comment by nmielnik** [comment] 2016-07-24 07:13
@martijndekuijper I believe this is a duplicate of #868 , let me know if you disagree.

I also think what you're talking about is somewhat similar to the functionality outline in #797 .

I don't believe there has been any additional progress with this other than the work @davideanderson did related to #797 , but I would be happy to accept a PR that addresses it.

This could also make sense as an extension, which could just restrict all input in the editor to only be tags that could be generated by the current toolbar state...

**Closed by nmielnik** 2016-07-24 07:13 UTC
Labels: enhancement

**Comment by martijndekuijper** [comment] 2016-07-25 14:12
Hey @nmielnik, thanks for letting me know and sorry that I didn't find these issues before posting :) Yes, I think that covers it, it's too bad that such a thing is not really possible yet (a lot of users at our service www.getrevue.co are asking for this, since they need to redo all the links all the time after pasting).
